const projects = [
  {
    id: 41,
    title: '25 + 5 Clock',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671188636/portfolio/challenges/41%20-%2025%2B5-CLOCK/Mobile_-_25_5-Clock_jiqdke.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/41%20-%2025%2B5-CLOCK/Desktop_-_25_5-Clock_wsdxsm.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/clock-timer.git',
    linkpreview: 'https://andr3sc0des.github.io/clock-timer',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, useState, useEffect, useRef, Functional Components, Responsive, setTimeout, Audio, Standart (ESLINT)',
    date: '11/11/2022'
  },
  {
    id: 40,
    title: 'Javascript Calculator',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/40%20-%20JAVASCRIPT-CALCULATOR/Mobile_-_Javascript_Calculator_niahk2.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/40%20-%20JAVASCRIPT-CALCULATOR/Desktop_-_Javascript_Calculator_skyjqm.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/javascript-calculator',
    linkpreview: 'https://andr3sc0des.github.io/javascript-calculator',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, Functional Components, useState, useRef, useEffect, Regex, Rendering Lists, Responsive, Props, Standard (ESLINT)',
    date: '06/11/2022'
  },
  {
    id: 39,
    title: 'Drum Machine',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/39%20-%20DRUM-MACHINE/Mobile_-_Drum_Machine_xdr2dw.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/39%20-%20DRUM-MACHINE/Desktop_-_Drum_Machine_c69yjl.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/drum-machine',
    linkpreview: 'https://andr3sc0des.github.io/drum-machine',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, Rendering Lists, Functional Components, useState, useEffect, Responsive, useRef, KeyEvents, Props, Standard (ESLINT), One Line Conditional',
    date: '04/11/2022'
  },
  {
    id: 38,
    title: 'Markdown Previewer',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/38%20-%20MARKDOWN-PREVIEWER/Mobile_-_Markdown_Previewer_clz1d0.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/38%20-%20MARKDOWN-PREVIEWER/Desktop_-_Markdown_Previewer_tx96rb.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/markdown-previewer',
    linkpreview: 'https://andr3sc0des.github.io/markdown-previewer',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, Functional Components, useState, useEffect, useRef, Responsive, DOM purify, Marked, Standard (ESLINT)',
    date: '28/11/2022'
  },
  {
    id: 37,
    title: 'Random Quote',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/37%20-%20RANDOM-QUOTE/Mobile_-_Random_Quotes_kpq8ev.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187591/portfolio/challenges/37%20-%20RANDOM-QUOTE/Desktop_-_Random_Quotes_cp54kz.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/random-quote',
    linkpreview: 'https://andr3sc0des.github.io/random-quote',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, Fetch API, Functional Components, useState, useEffect, Responsive',
    date: '26/11/2022'
  },
  {
    id: 31,
    title: 'Advice Generator App',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164496/portfolio/challenges/31.%20ADVICE%20GENERATOR%20APP/Mobile_-_Advice_generator_app_zmrguq.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164496/portfolio/challenges/31.%20ADVICE%20GENERATOR%20APP/Desktop_-_Advice_generator_app_xxu1tz.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/advice-generator-app',
    linkpreview: 'https://andr3sc0des.github.io/advice-generator-app',
    ref: 'https://www.frontendmentor.io/challenges/advice-generator-app-QdUG-13db',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, Functional Components, useState, useEffect, Fetch API, Responsive',
    date: '18/11/2022'
  },
  {
    id: 30,
    title: 'Intro Section With Dropdown',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164496/portfolio/challenges/30.%20INTRO%20SECTION%20WITH%20DROPDOWN/Mobile_-_Intro_section_with_dropdown_navigation_mcjrnn.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164496/portfolio/challenges/30.%20INTRO%20SECTION%20WITH%20DROPDOWN/Desktop_-_Intro_section_with_dropdown_navigation_qoxy5y.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/section-dropdown',
    linkpreview: 'https://andr3sc0des.github.io/section-dropdown',
    ref: 'https://www.frontendmentor.io/challenges/intro-section-with-dropdown-navigation-ryaPetHE5',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, Functional Components, useState, useEffect, Rendering Lists, Props, Responsive',
    date: '09/11/2022'

  },
  {
    id: 29,
    title: 'Expenses Chart',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164496/portfolio/challenges/29.%20EXPENSES-CHART/Mobile_-_Expenses_chart_component_bvsrkz.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/29.%20EXPENSES-CHART/Desktop_-_Expenses_chart_component_qbxroc.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/expenses-chart',
    linkpreview: 'https://andr3sc0des.github.io/expenses-chart',
    ref: 'https://www.frontendmentor.io/challenges/expenses-chart-component-e7yJBUdjwt',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, Responsive, Functional Components, Hooks, useState, useEffect, Rendering Lists, One line conditionals, Conditional Styling',
    date: '08/11/2022'
  },
  {
    id: 28,
    title: 'Interactive Card',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/28.%20INTERACTIVE-CARD/Mobile_-_Interactive_card_details_form_jto7yl.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/28.%20INTERACTIVE-CARD/Desktop_-_Interactive_card_details_form_lrmh6m.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/interactive-card',
    linkpreview: 'https://andr3sc0des.github.io/interactive-card',
    ref: 'https://www.frontendmentor.io/challenges/interactive-card-details-form-XpS8cKZDWw',
    description: 'Breve descripción',
    tags: 'HTML, Tailwind, Javascript, React, Vite, Regex, Class Component, CSS Tooltips, States, Validation Form',
    date: '04/11/2022'
  },
  {
    id: 27,
    title: 'Notifications Page',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/27.%20NOTIFICATIONS%20PAGE/Mobile_-_Notifications_page_l5znc0.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/27.%20NOTIFICATIONS%20PAGE/Desktop_-_Notifications_page_kihftc.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/notifications-page',
    linkpreview: 'https://andr3sc0des.github.io/notifications-page',
    ref: 'https://www.frontendmentor.io/challenges/notifications-page-DqK5QAmKbC',
    description: 'Breve descripción',
    tags: 'HTML, Javascript, React, Vite, Tailwind, Class Component, responsive, mobile-first, states',
    date: '02/11/2022'
  },
  {
    id: 26,
    title: 'Huddle Landing Page With Curved Sections',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/26.%20CURVED%20SECTIONS/Mobile_-_Huddle_landing_page_with_curved_sections_gi2ouv.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/26.%20CURVED%20SECTIONS/Desktop_-_Huddle_landing_page_with_curved_sections_ctciu6.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/huddle-curved',
    linkpreview: 'https://andr3sc0des.github.io/huddle-curved',
    ref: 'https://www.frontendmentor.io/challenges/huddle-landing-page-with-curved-sections-5ca5ecd01e82137ec91a50f2',
    description: 'Breve descripción',
    tags: 'HTML, Javascript, React, Vite, Tailwind, Regex, Validation Form, Class Component, Responsive',
    date: '29/10/2022'
  },
  {
    id: 25,
    title: 'Fylo Landing Page',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164494/portfolio/challenges/25.%20FYLO%20LANDING%20PAGE/Mobile_-_Fylo_landing_page_with_two_column_layout_jceag0.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164494/portfolio/challenges/25.%20FYLO%20LANDING%20PAGE/Mobile_-_Fylo_landing_page_with_two_column_layout_rprgus.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/fylo-landing-page',
    linkpreview: 'https://andr3sc0des.github.io/fylo-landing-page',
    ref: 'https://www.frontendmentor.io/challenges/fylo-landing-page-with-two-column-layout-5ca5ef041e82137ec91a50f5',
    description: 'Breve descripción',
    tags: 'HTML, Javascript, React, Tailwind, Vite, Mobile-first, Responsive, Class Component, Layout, Background properties',
    date: '27/10/2022'
  },
  {
    id: 24,
    title: 'Huddle Landing Page',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671189454/portfolio/challenges/24.%20HUDDLE%20LANDING%20PAGE/Mobile_-_Huddle_landing_page_with_alternating_feature_blocks_rbiw1p.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671189454/portfolio/challenges/24.%20HUDDLE%20LANDING%20PAGE/Desktop_-_Huddle_landing_page_with_alternating_feature_blocks_wjjhk6.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/huddle-landing-page-alternate',
    linkpreview: 'https://andr3sc0des.github.io/huddle-landing-page-alternate',
    ref: 'https://www.frontendmentor.io/challenges/huddle-landing-page-with-alternating-feature-blocks-5ca5f5981e82137ec91a5100',
    description: 'Breve descripción',
    tags: 'HTML, Tailwind, Hover, Background properties, Layout, Flexbox, Responsive, Grid, Mobile-first',
    date: '26/10/2022'
  },
  {
    id: 23,
    title: 'Clipboard Landing Page Master',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109548/portfolio/challenges/23.%20CLIPBOARD%20LANDING%20PAGE%20MASTER/Mobile_-_Clipboard_landing_page_-_jkc0t6.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109548/portfolio/challenges/23.%20CLIPBOARD%20LANDING%20PAGE%20MASTER/Desktop_-_Clipboard_landing_page_-_kfnu7l.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/clipboard-landing-page',
    linkpreview: 'https://andr3sc0des.github.io/clipboard-landing-page',
    ref: 'https://www.frontendmentor.io/challenges/clipboard-landing-page-5cc9bccd6c4c91111378ecb9',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Background properties, Responsive, Grid, Flexbox',
    date: '16/10/2022'
  },
  {
    id: 22,
    title: 'News Homepage',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109554/portfolio/challenges/22.%20NEWS%20HOMEPAGE/Mobile_-_News_homepage_-_ht2eez.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109553/portfolio/challenges/22.%20NEWS%20HOMEPAGE/Desktop_-_News_homepage_-_wugxwu.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/news-homepage',
    linkpreview: 'https://andr3sc0des.github.io/news-homepage',
    ref: 'https://www.frontendmentor.io/challenges/fylo-data-storage-component-1dZPRbV5n',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Pseudo-classes, Sibling Combinators, Mobile Menu, Layout, Grid, Transitions, Background properties',
    date: '21/10/2022'
  },
  {
    id: 21,
    title: 'Fylo Data Storage Component Master',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109553/portfolio/challenges/21.%20FYLO%20DATA%20STORAGE%20COMPONENT%20MASTER/Mobile_-_Fylo_data_storage_component_-_w74axv.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109553/portfolio/challenges/21.%20FYLO%20DATA%20STORAGE%20COMPONENT%20MASTER/Desktop_-_Fylo_data_storage_component_-_a7kxci.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/fylo-data-storage-component.git',
    linkpreview: 'https://andr3sc0des.github.io/fylo-data-storage-component',
    ref: 'https://www.frontendmentor.io/challenges/fylo-data-storage-component-1dZPRbV5n',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, Gradient, Background properties, Tooltips, Flexbox, Responsive, Pseudo-Classes, DOM Manipulation, Vendor Prefixes',
    date: '16/10/2022'
  },
  {
    id: 20,
    title: 'Sidebar Responsive',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109553/portfolio/challenges/20%20NAVBAR%20RESPONSIVE/Mobile_-_SIDEBAR_RESPONSIVE_-_COMPONENT_-_srcrnd.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109553/portfolio/challenges/20%20NAVBAR%20RESPONSIVE/Desktop_-_SIDEBAR_RESPONSIVE_-_COMPONENT_-_jbcqw5.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/sidebar-responsive.git',
    linkpreview: 'https://andr3sc0des.github.io/sidebar-responsive',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, sass modifiers, event listeners, transition, CSS selectors, desktop-first workflow',
    date: '07/10/2022'
  },
  {
    id: 19,
    title: 'Nav With Dropdown Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109552/portfolio/challenges/19.%20NAV%20WITH%20DROPDOWN%20COMPONENT/Mobile_-_NAV_WITH_DROPDOWN_-_COMPONENT_-_e8jskj.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109552/portfolio/challenges/19.%20NAV%20WITH%20DROPDOWN%20COMPONENT/DESKTOP_-_NAV_WITH_DROPDOWN_-_COMPONENT_-_efolay.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/nav-with-dropdown-component.git',
    linkpreview: 'https://andr3sc0des.github.io/nav-with-dropdown-component',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, sass modifiers, event listeners, transition, hover states',
    date: '06/10/2022'
  },
  {
    id: 18,
    title: 'Testimonials Grid Section Main',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109552/portfolio/challenges/18.%20TESTIMONIALS%20GRID%20SECTION%20MAIN/Mobile_-_Testimonial_grid_section_main_-_wekz57.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109552/portfolio/challenges/18.%20TESTIMONIALS%20GRID%20SECTION%20MAIN/Desktop_-_Testimonial_grid_section_main_-_zeuh3a.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/testimonial-grid-section-main.git',
    linkpreview: 'https://andr3sc0des.github.io/testimonial-grid-section-main',
    ref: 'https://www.frontendmentor.io/challenges/testimonials-grid-section-Nnw6J7Un7',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Grid, responsive, background properties, desktop-first workflow',
    date: '17/10/2022'
  },
  {
    id: 17,
    title: 'Ping Single Column Coming Soon Page',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164494/portfolio/challenges/17.%20PING%20SINGLE%20COLUMN%20COMING%20SOON%20PAGE/Mobile_-_Ping_coming_soon_page_brk8tl.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164494/portfolio/challenges/17.%20PING%20SINGLE%20COLUMN%20COMING%20SOON%20PAGE/Desktop_-_Ping_coming_soon_page_ttq3cd.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/ping-single-column-coming-soon-page.git',
    linkpreview: 'https://andr3sc0des.github.io/ping-single-column-coming-soon-page',
    ref: 'https://www.frontendmentor.io/challenges/ping-single-column-coming-soon-page-5cadd051fec04111f7b848da',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React ,Vite , Class Component, validation Forms, responsive, regex, states, componentDidMount',
    date: '16/10/2022'
  },
  {
    id: 16,
    title: 'Intro Component With Signup From Master',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164494/portfolio/challenges/16.%20INTRO%20COMPONENT%20WITH%20SIGNUP%20FROM%20MASTER/Mobile_-_Intro_component_with_sign_up_form_duiktm.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164494/portfolio/challenges/16.%20INTRO%20COMPONENT%20WITH%20SIGNUP%20FROM%20MASTER/desktop_-_intro_component_sign_up_sbvhmm.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/intro-component-with-sign-up-form.git',
    linkpreview: 'https://andr3sc0des.github.io/intro-component-with-sign-up-form',
    ref: 'https://www.frontendmentor.io/challenges/intro-component-with-signup-form-5cf91bd49edda32581d28fd1',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Javascript, React, Vite, validation Forms, responsive, regex, Class Component, States, componentDidMount',
    date: '16/10/2022'
  },
  {
    id: 15,
    title: 'Base Apparel Comming Soon Master',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164495/portfolio/challenges/15.%20BASE%20APPAREL%20COMMING%20SOON%20MASTER/Mobile_-_Base_Apparel_coming_soon_page_evyynz.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671164494/portfolio/challenges/15.%20BASE%20APPAREL%20COMMING%20SOON%20MASTER/Desktop_-_Base_Apparel_coming_soon_page_xsqurz.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/base-apparel-coming-soon-page.git',
    linkpreview: 'https://andr3sc0des.github.io/base-apparel-coming-soon-page',
    ref: 'https://www.frontendmentor.io/challenges/base-apparel-coming-soon-page-5d46b47f8db8a7063f9331a0',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, React, Vite, Javascript, validation Forms, responsive, sass modifiers, Class Component',
    date: '14/10/2022'
  },
  {
    id: 14,
    title: 'FAQ Accordion',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109552/portfolio/challenges/14.%20FAQ%20ACCORDION/Mobile_-_FAQ_Accordion_Card_-_bsywsv.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109551/portfolio/challenges/14.%20FAQ%20ACCORDION/Desktop_-_FAQ_Accordion_Card_-_byycep.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/faq-accordion-card',
    linkpreview: 'https://andr3sc0des.github.io/faq-accordion-card',
    ref: 'https://www.frontendmentor.io/challenges/faq-accordion-card-XlyjD0Oam',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, translate, background properties, transition, event listener, desktop-first workflow',
    date: '09/10/2022'
  },
  {
    id: 33,
    title: 'Personal Portfolio',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187591/portfolio/challenges/33%20-%20PERSONAL-PORTFOLIO/Mobile_-_Personal_Portfolio_mpwpzo.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187591/portfolio/challenges/33%20-%20PERSONAL-PORTFOLIO/Desktop_-_Personal_Portfolio_yqaysu.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/personal-portfolio',
    linkpreview: 'https://andr3sc0des.github.io/personal-portfolio',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, Responsive, Fixed Navbar, Smooth Scroll',
    date: '24/11/2022'
  },
  {
    id: 34,
    title: 'Landing Page',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187591/portfolio/challenges/34%20-%20LANDING-PAGE/Mobile_-_Landing_Page_v9rxms.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671190775/portfolio/challenges/34%20-%20LANDING-PAGE/Desktop_-_Landing_Page_ly2vor.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/landing-page-trombones',
    linkpreview: 'https://andr3sc0des.github.io/landing-page-trombones',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, Fixed Navbar, Video, Responsive',
    date: '24/11/2022'
  },
  {
    id: 35,
    title: 'Tribute Page',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187591/portfolio/challenges/35%20-%20TRIBUTE-PAGE/Mobile_-_Tribute_Page_bxogmc.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187591/portfolio/challenges/35%20-%20TRIBUTE-PAGE/Desktop_-_Tribute_Page_fgaq0t.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/tribute-page',
    linkpreview: 'https://andr3sc0des.github.io/tribute-page',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, Responsive',
    date: '25/11/2022'
  },
  {
    id: 36,
    title: 'Documentation',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/36%20-%20DOCUMENTATION/Mobile_-_Documentation_Page_zkojpy.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187592/portfolio/challenges/36%20-%20DOCUMENTATION/Desktop_-_Documentation_Page_cbxzkr.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/documentation',
    linkpreview: 'https://andr3sc0des.github.io/documentation',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, Sidebar, Responsive, Scroll Smooth,',
    date: '26/11/2022'
  },
  {
    id: 32,
    title: 'Survey Form',
    mobileimage: '',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671187591/portfolio/challenges/32%20-%20SURVEY-FORM/Desktop_-_Survery_Form_rc6y84.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/survey-form',
    linkpreview: 'https://andr3sc0des.github.io/survey-form',
    ref: false,
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, Forms',
    date: '23/11/2022'
  },
  {
    id: 13,
    title: 'Article Preview',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109551/portfolio/challenges/13.%20ARTICLE%20PREVIEW/Mobile_-_Article_preview_component_-_ivfchb.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109551/portfolio/challenges/13.%20ARTICLE%20PREVIEW/Desktop_-_Article_preview_component_-_b881b3.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/article-preview',
    linkpreview: 'https://andr3sc0des.github.io/article-preview',
    ref: 'https://www.frontendmentor.io/challenges/article-preview-component-dYBN_pYFT',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, transition, desktop-first workflow, event listener, pseudo-classes',
    date: '08/10/2022'
  },
  {
    id: 12,
    title: 'Interactive Rating Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/12.%20INTERACTIVE_RATING_COMPONENT/Mobile_-_Interactive_rating_component_-_ydybcb.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/12.%20INTERACTIVE_RATING_COMPONENT/Desktop_-_Interactive_rating_component_-_xk89bu.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/interactive-rating-component',
    linkpreview: 'https://andr3sc0des.github.io/interactive-rating-component',
    ref: 'https://www.frontendmentor.io/challenges/interactive-rating-component-koxpeBUmI',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, CSS selectors, responsive, desktop-first workflow, event listeners',
    date: '08/10/2022'
  },
  {
    id: 11,
    title: 'Huddle Landing Page',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/11.%20HUDDLE%20LANDING%20PAGE/Mobile_-_Huddle_landing_page_with_single_introductory_section_-_oxps7f.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/11.%20HUDDLE%20LANDING%20PAGE/Desktop_-_Huddle_landing_page_with_single_introductory_section_-_peux0x.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/huddle-landing-page',
    linkpreview: 'https://andr3sc0des.github.io/huddle-landing-page',
    ref: 'https://www.frontendmentor.io/challenges/huddle-landing-page-with-a-single-introductory-section-B_2Wvxgi0',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, layout, background properties, responsive, desktop-first workflow',
    date: '05/10/2022'
  },
  {
    id: 10,
    title: 'Single Price Grid Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109549/portfolio/challenges/10.%20SINGLE%20PRICE%20GRID%20COMPONENT/Mobile_-_Single_Price_Grid_Component_-_wdivk7.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109549/portfolio/challenges/10.%20SINGLE%20PRICE%20GRID%20COMPONENT/Desktop_-_Single_Price_Grid_Component_-_cpnrnb.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/single-price-grid-component',
    linkpreview: 'https://andr3sc0des.github.io/single-price-grid-component',
    ref: 'https://www.frontendmentor.io/challenges/single-price-grid-component-5ce41129d0ff452fec5abbbc',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, grid, desktop-first workflow',
    date: '05/10/2022'
  },
  {
    id: 9,
    title: 'Four Card Feature',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109548/portfolio/challenges/09.%20FOUR%20CARD%20FEATURE/Mobile_-_Four_card_feature_section_-_cvlodd.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109548/portfolio/challenges/09.%20FOUR%20CARD%20FEATURE/Desktop_-_Four_card_feature_section_-_weost4.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/four-card-feature-section',
    linkpreview: 'https://andr3sc0des.github.io/four-card-feature-section',
    ref: 'https://www.frontendmentor.io/challenges/four-card-feature-section-weK1eFYK',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, sass modifiers, layout, translate, flexbox, responsive, desktop-first workflow',
    date: '05/10/2022'
  },
  {
    id: 8,
    title: 'Social Proof Section',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109548/portfolio/challenges/08.%20SOCIAL%20PROOF%20SECTION/Mobile_-_Social_proof_section_-_zesisj.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109548/portfolio/challenges/08.%20SOCIAL%20PROOF%20SECTION/Desktop_-_Social_proof_section_-_n2szy5.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/social-proof-section',
    linkpreview: 'https://andr3sc0des.github.io/social-proof-section',
    ref: 'https://www.frontendmentor.io/challenges/social-proof-section-6e0qTv_bA',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, layout, translate, responsive, desktop-first workflow',
    date: '05/10/2022'
  },
  {
    id: 7,
    title: 'Profile Card Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109548/portfolio/challenges/07.%20PROFILE%20CARD%20COMPONENT/Mobile_-_Profile_card_component_-_wuvszu.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109551/portfolio/challenges/07.%20PROFILE%20CARD%20COMPONENT/Desktop_-_Profile_card_component_-_c8ib9k.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/profile-card-component',
    linkpreview: 'https://andr3sc0des.github.io/profile-card-component',
    ref: 'https://www.frontendmentor.io/challenges/profile-card-component-cfArpWshJ',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, desktop-first workflow, background properties',
    date: '05/10/2022'
  },
  {
    id: 6,
    title: '3 Column Preview Card Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109551/portfolio/challenges/06.%203%20COLUMN%20PREVIEW%20CARD%20COMPONENT/Mobile_-_3-column_preview_card_component_-_n6e7xg.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109554/portfolio/challenges/06.%203%20COLUMN%20PREVIEW%20CARD%20COMPONENT/Desktop_-_3-column_preview_card_component_-_lq6yia.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/3-column-preview-card-component',
    linkpreview: 'https://andr3sc0des.github.io/3-column-preview-card-component',
    ref: 'https://www.frontendmentor.io/challenges/3column-preview-card-component-pH92eAR2-',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, grid, desktop-first workflow',
    date: '05/10/2022'
  },
  {
    id: 5,
    title: 'Stats Preview Card Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109551/portfolio/challenges/05.%20STATS%20PREVIEW%20CARD%20COMPONENT/Mobile_-_Stats_preview_card_component_-_nqewjk.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/05.%20STATS%20PREVIEW%20CARD%20COMPONENT/Desktop_-_Stats_preview_card_component_-_ij6lko.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/stats-preview-card-component',
    linkpreview: 'https://andr3sc0des.github.io/stats-preview-card-component',
    ref: 'https://www.frontendmentor.io/challenges/stats-preview-card-component-8JqbgoU62',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, desktop-first workflow',
    date: '04/10/2022'
  },
  {
    id: 4,
    title: 'Order Summary Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109551/portfolio/challenges/04.%20ORDER%20SUMMARY%20COMPONENT/Mobile_-_Order_summary_card_-_afs79a.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/04.%20ORDER%20SUMMARY%20COMPONENT/Desktop_-_Order_summary_card_-_dkfiip.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/order-summary-card',
    linkpreview: 'https://andr3sc0des.github.io/order-summary-card',
    ref: 'https://www.frontendmentor.io/challenges/order-summary-component-QlPmajDUj',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, background properties, desktop-first workflow',
    date: '04/10/2022'
  },
  {
    id: 3,
    title: 'NFT Preview Card Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109549/portfolio/challenges/03.%20NFT%20PREVIEW%20CARD%20COMPONENT/Mobile_-_NFT_preview_card_component_-_s81msj.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109549/portfolio/challenges/03.%20NFT%20PREVIEW%20CARD%20COMPONENT/Desktop_-_NFT_preview_card_component_-_hck1mk.webp',
    scroll: true,
    linksource: 'https://github.com/Andr3sC0des/nft-preview-card-component',
    linkpreview: 'https://andr3sc0des.github.io/nft-preview-card-component',
    ref: 'https://www.frontendmentor.io/challenges/nft-preview-card-component-SbdUL_w0U',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, hover states, desktop-first workflow',
    date: '04/10/2022'
  },
  {
    id: 2,
    title: 'QR code component',
    mobileimage: '',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/02.%20QR%20CODE%20COMPONENT/Desktop_-_QR_code_component_-_kziqxu.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/qr-code-component',
    linkpreview: 'https://andr3sc0des.github.io/qr-code-component',
    ref: 'https://www.frontendmentor.io/challenges/qr-code-component-iux_sIO_H',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox',
    date: '04/10/2022'
  },
  {
    id: 1,
    title: 'Product Preview Card Component',
    mobileimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109549/portfolio/challenges/01%20-%20PRODUCT%20REVIEW%20CARD/Mobile_-_Product_preview_card_component_fdqs0p.webp',
    desktopimage: 'https://res.cloudinary.com/dbihhif3d/image/upload/v1671109550/portfolio/challenges/01%20-%20PRODUCT%20REVIEW%20CARD/Desktop_-_Product_preview_card_component_pxf4h7.webp',
    scroll: false,
    linksource: 'https://github.com/Andr3sC0des/product-preview-card-component',
    linkpreview: 'https://andr3sc0des.github.io/product-preview-card-component',
    ref: 'https://www.frontendmentor.io/challenges/product-preview-card-component-GO7UmttRfa',
    description: 'Breve descripción',
    tags: 'HTML, CSS, SASS, Flexbox, responsive, desktop-first workflow',
    date: '02/10/2022'
  }
]

export default projects
